openapi: 3.2.0
info:
  description: Documentation of TheTVDB API V4.
  title: TVDB API V4 Awards API
  version: 4.7.10
  x-last-validated: '2026-05-30'
  x-spec-source: https://github.com/thetvdb/v4-api/blob/main/docs/swagger.yml
servers:
- url: https://api4.thetvdb.com/v4
  description: TheTVDB v4 API production
security:
- bearerAuth: []
tags:
- name: Awards
paths:
  /awards:
    get:
      description: Returns a list of award base records
      operationId: getAllAwards
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/AwardBaseRecord'
                    type: array
                  status:
                    type: string
                type: object
              examples:
                GetAllAwards200Example:
                  summary: Default getAllAwards 200 response
                  x-microcks-default: true
                  value:
                    data:
                    - id: 12345
                      name: Example Name
                    status: Continuing
        '401':
          description: Unauthorized
      tags:
      - Awards
      summary: TheTVDB Get All Awards
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /awards/{id}:
    get:
      description: Returns a single award base record
      operationId: getAward
      parameters:
      - description: id
        in: path
        name: id
        required: true
        schema:
          type: number
        example: 12345
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/AwardBaseRecord'
                  status:
                    type: string
                type: object
              examples:
                GetAward200Example:
                  summary: Default getAward 200 response
                  x-microcks-default: true
                  value:
                    data:
                      id: 12345
                      name: Example Name
                    status: Continuing
        '400':
          description: Invalid awards id
        '401':
          description: Unauthorized
        '404':
          description: Awards not found
      tags:
      - Awards
      summary: TheTVDB Get Award
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /awards/{id}/extended:
    get:
      description: Returns a single award extended record
      operationId: getAwardExtended
      parameters:
      - description: id
        in: path
        name: id
        required: true
        schema:
          type: number
        example: 12345
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/AwardExtendedRecord'
                  status:
                    type: string
                type: object
              examples:
                GetAwardExtended200Example:
                  summary: Default getAwardExtended 200 response
                  x-microcks-default: true
                  value:
                    data:
                      categories:
                      - allowCoNominees: true
                        award:
                          id: 12345
                          name: Example Name
                        forMovies: true
                        forSeries: true
                        id: 12345
                        name: Example Name
                      id: 12345
                      name: Example Name
                      score: 100
                    status: Continuing
        '400':
          description: Invalid awards id
        '401':
          description: Unauthorized
        '404':
          description: Awards not found
      tags:
      - Awards
      summary: TheTVDB Get Award Extended
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    AwardCategoryBaseRecord:
      description: base award category record
      properties:
        allowCoNominees:
          type: boolean
          x-go-name: AllowCoNominees
          example: true
        award:
          $ref: '#/components/schemas/AwardBaseRecord'
        forMovies:
          type: boolean
          x-go-name: ForMovies
          example: true
        forSeries:
          type: boolean
          x-go-name: ForSeries
          example: true
        id:
          format: int64
          type: integer
          x-go-name: ID
          example: 12345
        name:
          type: string
          example: Example Name
      type: object
      x-go-package: github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model
    AwardBaseRecord:
      description: base award record
      properties:
        id:
          type: integer
          example: 12345
        name:
          type: string
          example: Example Name
      type: object
      x-go-package: github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model
    AwardExtendedRecord:
      description: extended award record
      properties:
        categories:
          items:
            $ref: '#/components/schemas/AwardCategoryBaseRecord'
          type: array
          x-go-name: Categories
        id:
          type: integer
          example: 12345
        name:
          type: string
          example: Example Name
        score:
          format: int64
          type: integer
          x-go-name: Score
          example: 100
      type: object
      x-go-package: github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
