=== api-evangelist/tvdb/json-schema/tvdb-list-base-record-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/tvdb/refs/heads/main/json-schema/tvdb-list-base-record-schema.json",
  "title": "ListBaseRecord",
  "description": "base list record",
  "properties": {
    "aliases": {
      "items": {
        "description": "An alias model, which can be associated with a series, season, movie, person, or list.",
        "properties": {
          "language": {
            "type": "string",
            "maximum": 4,
            "description": "A 3-4 character string indicating the language of the alias, as defined in Language.",
            "example": "eng"
          },
          "name": {
            "type": "string",
            "maximum": 100,
            "description": "A string containing the alias itself.",
            "example": "Example Name"
          }
        },
        "type": "object"
      },
      "type": "array",
      "x-go-name": "Aliases"
    },
    "id": {
      "format": "int64",
      "type": "integer",
      "x-go-name": "ID",
      "example": 12345
    },
    "image": {
      "type": "string",
      "example": "https://artworks.thetvdb.com/banners/example.jpg"
    },
    "imageIsFallback": {
      "type": "boolean",
      "example": true
    },
    "isOfficial": {
      "type": "boolean",
      "x-go-name": "IsOfficial",
      "example": true
    },
    "name": {
      "type": "string",
      "example": "Example Name"
    },
    "nameTranslations": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "x-go-name": "NameTranslations",
      "example": [
        "example"
      ]
    },
    "overview": {
      "type": "string",
      "example": "A descriptive paragraph of text."
    },
    "overviewTranslations": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "x-go-name": "OverviewTranslations",
      "example": [
        "example"
      ]
    },
    "remoteIds": {
      "items": {
        "description": "remote id record",
        "properties": {
          "id": {
            "type": "string",
            "x-go-name": "ID",
            "example": "abc123"
          },
          "type": {
            "format": "int64",
            "type": "integer",
            "x-go-name": "Type",
            "example": 12345
          },
          "sourceName": {
            "type": "string",
            "x-go-name": "SourceName",
            "example": "example"
          }
        },
        "type": "object",
        "x-go-package": "github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model"
      },
      "type": "array",
      "x-go-name": "RemoteIDs"
    },
    "tags": {
      "items": {
        "description": "tag option record",
        "properties": {
          "helpText": {
            "type": "string",
            "example": "example"
          },
          "id": {
            "format": "int64",
            "type": "integer",
            "x-go-name": "ID",
            "example": 12345
          },
          "name": {
            "type": "string",
            "x-go-name": "Name",
            "example": "Example Name"
          },
          "tag": {
            "format": "int64",
            "type": "integer",
            "x-go-name": "Tag",
            "example": 12345
          },
          "tagName": {
            "type": "string",
            "x-go-name": "TagName",
            "example": "example"
          }
        },
        "type": "object",
        "x-go-package": "github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model"
      },
      "type": "array",
      "x-go-name": "TagOptions"
    },
    "score": {
      "type": "integer",
      "example": 100
    },
    "url": {
      "type": "string",
      "example": "https://artworks.thetvdb.com/banners/example.jpg"
    }
  },
  "type": "object"
}

=== api-evangelist/tvdb/examples/tvdb-list-base-record-example.json
{
  "aliases": [
    {
      "language": "eng",
      "name": "Example Name"
    }
  ],
  "id": 12345,
  "image": "https://artworks.thetvdb.com/banners/example.jpg",
  "imageIsFallback": true,
  "isOfficial": true,
  "name": "Example Name",
  "nameTranslations": [
    "example"
  ],
  "overview": "A descriptive paragraph of text.",
  "overviewTranslations": [
    "example"
  ],
  "remoteIds": [
    {
      "id": "abc123",
      "type": 12345,
      "sourceName": "example"
    }
  ],
  "tags": [
    {
      "helpText": "example",
      "id": 12345,
      "name": "Example Name",
      "tag": 12345,
      "tagName": "example"
    }
  ],
  "score": 100,
  "url": "https://artworks.thetvdb.com/banners/example.jpg"
}
