=== api-evangelist/tvdb/json-schema/tvdb-character-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/tvdb/refs/heads/main/json-schema/tvdb-character-schema.json",
  "title": "Character",
  "description": "character record",
  "properties": {
    "aliases": {
      "items": {
        "description": "An alias model, which can be associated with a series, season, movie, person, or list.",
        "properties": {
          "language": {
            "type": "string",
            "maximum": 4,
            "description": "A 3-4 character string indicating the language of the alias, as defined in Language.",
            "example": "eng"
          },
          "name": {
            "type": "string",
            "maximum": 100,
            "description": "A string containing the alias itself.",
            "example": "Example Name"
          }
        },
        "type": "object"
      },
      "type": "array",
      "x-go-name": "Aliases"
    },
    "episode": {
      "description": "base record info",
      "properties": {
        "image": {
          "type": "string",
          "x-go-name": "Image",
          "example": "https://artworks.thetvdb.com/banners/example.jpg"
        },
        "name": {
          "type": "string",
          "x-go-name": "Name",
          "example": "Example Name"
        },
        "year": {
          "type": "string",
          "example": "2024"
        }
      },
      "type": "object",
      "x-go-package": "github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model"
    },
    "episodeId": {
      "type": "integer",
      "nullable": true,
      "example": 12345
    },
    "id": {
      "format": "int64",
      "type": "integer",
      "x-go-name": "ID",
      "example": 12345
    },
    "image": {
      "type": "string",
      "example": "https://artworks.thetvdb.com/banners/example.jpg"
    },
    "isFeatured": {
      "type": "boolean",
      "x-go-name": "IsFeatured",
      "example": true
    },
    "movieId": {
      "type": "integer",
      "nullable": true,
      "example": 12345
    },
    "movie": {
      "description": "base record info",
      "properties": {
        "image": {
          "type": "string",
          "x-go-name": "Image",
          "example": "https://artworks.thetvdb.com/banners/example.jpg"
        },
        "name": {
          "type": "string",
          "x-go-name": "Name",
          "example": "Example Name"
        },
        "year": {
          "type": "string",
          "example": "2024"
        }
      },
      "type": "object",
      "x-go-package": "github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model"
    },
    "name": {
      "type": "string",
      "example": "Example Name"
    },
    "nameTranslations": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "x-go-name": "NameTranslations",
      "example": [
        "example"
      ]
    },
    "overviewTranslations": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "x-go-name": "OverviewTranslations",
      "example": [
        "example"
      ]
    },
    "peopleId": {
      "type": "integer",
      "example": 12345
    },
    "personImgURL": {
      "type": "string",
      "example": "https://artworks.thetvdb.com/banners/example.jpg"
    },
    "peopleType": {
      "type": "string",
      "example": "example"
    },
    "seriesId": {
      "type": "integer",
      "nullable": true,
      "example": 12345
    },
    "series": {
      "description": "base record info",
      "properties": {
        "image": {
          "type": "string",
          "x-go-name": "Image",
          "example": "https://artworks.thetvdb.com/banners/example.jpg"
        },
        "name": {
          "type": "string",
          "x-go-name": "Name",
          "example": "Example Name"
        },
        "year": {
          "type": "string",
          "example": "2024"
        }
      },
      "type": "object",
      "x-go-package": "github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model"
    },
    "sort": {
      "format": "int64",
      "type": "integer",
      "x-go-name": "Sort",
      "example": 12345
    },
    "tagOptions": {
      "items": {
        "description": "tag option record",
        "properties": {
          "helpText": {
            "type": "string",
            "example": "example"
          },
          "id": {
            "format": "int64",
            "type": "integer",
            "x-go-name": "ID",
            "example": 12345
          },
          "name": {
            "type": "string",
            "x-go-name": "Name",
            "example": "Example Name"
          },
          "tag": {
            "format": "int64",
            "type": "integer",
            "x-go-name": "Tag",
            "example": 12345
          },
          "tagName": {
            "type": "string",
            "x-go-name": "TagName",
            "example": "example"
          }
        },
        "type": "object",
        "x-go-package": "github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model"
      },
      "type": "array",
      "x-go-name": "TagOptions"
    },
    "type": {
      "format": "int64",
      "type": "integer",
      "x-go-name": "Type",
      "example": 12345
    },
    "url": {
      "type": "string",
      "x-go-name": "URL",
      "example": "https://artworks.thetvdb.com/banners/example.jpg"
    },
    "personName": {
      "type": "string",
      "example": "example"
    }
  },
  "type": "object"
}

=== api-evangelist/tvdb/examples/tvdb-character-example.json
{
  "aliases": [
    {
      "language": "eng",
      "name": "Example Name"
    }
  ],
  "episode": {
    "image": "https://artworks.thetvdb.com/banners/example.jpg",
    "name": "Example Name",
    "year": "2024"
  },
  "episodeId": 12345,
  "id": 12345,
  "image": "https://artworks.thetvdb.com/banners/example.jpg",
  "isFeatured": true,
  "movieId": 12345,
  "movie": {
    "image": "https://artworks.thetvdb.com/banners/example.jpg",
    "name": "Example Name",
    "year": "2024"
  },
  "name": "Example Name",
  "nameTranslations": [
    "example"
  ],
  "overviewTranslations": [
    "example"
  ],
  "peopleId": 12345,
  "personImgURL": "https://artworks.thetvdb.com/banners/example.jpg",
  "peopleType": "example",
  "seriesId": 12345,
  "series": {
    "image": "https://artworks.thetvdb.com/banners/example.jpg",
    "name": "Example Name",
    "year": "2024"
  },
  "sort": 12345,
  "tagOptions": [
    {
      "helpText": "example",
      "id": 12345,
      "name": "Example Name",
      "tag": 12345,
      "tagName": "example"
    }
  ],
  "type": 12345,
  "url": "https://artworks.thetvdb.com/banners/example.jpg",
  "personName": "example"
}
