=== api-evangelist/tvdb/json-schema/tvdb-people-base-record-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/tvdb/refs/heads/main/json-schema/tvdb-people-base-record-schema.json",
  "title": "PeopleBaseRecord",
  "description": "base people record",
  "properties": {
    "aliases": {
      "items": {
        "description": "An alias model, which can be associated with a series, season, movie, person, or list.",
        "properties": {
          "language": {
            "type": "string",
            "maximum": 4,
            "description": "A 3-4 character string indicating the language of the alias, as defined in Language.",
            "example": "eng"
          },
          "name": {
            "type": "string",
            "maximum": 100,
            "description": "A string containing the alias itself.",
            "example": "Example Name"
          }
        },
        "type": "object"
      },
      "type": "array",
      "x-go-name": "Aliases"
    },
    "id": {
      "format": "int64",
      "type": "integer",
      "x-go-name": "ID",
      "example": 12345
    },
    "image": {
      "type": "string",
      "example": "https://artworks.thetvdb.com/banners/example.jpg"
    },
    "lastUpdated": {
      "type": "string",
      "example": "2024-01-15"
    },
    "name": {
      "type": "string",
      "example": "Example Name"
    },
    "nameTranslations": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "x-go-name": "NameTranslations",
      "example": [
        "example"
      ]
    },
    "overviewTranslations": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "x-go-name": "OverviewTranslations",
      "example": [
        "example"
      ]
    },
    "score": {
      "format": "int64",
      "type": "integer",
      "x-go-name": "Score",
      "example": 100
    }
  },
  "type": "object"
}

=== api-evangelist/tvdb/examples/tvdb-people-base-record-example.json
{
  "aliases": [
    {
      "language": "eng",
      "name": "Example Name"
    }
  ],
  "id": 12345,
  "image": "https://artworks.thetvdb.com/banners/example.jpg",
  "lastUpdated": "2024-01-15",
  "name": "Example Name",
  "nameTranslations": [
    "example"
  ],
  "overviewTranslations": [
    "example"
  ],
  "score": 100
}
