=== api-evangelist/tvdb/json-schema/tvdb-search-result-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/tvdb/refs/heads/main/json-schema/tvdb-search-result-schema.json",
  "title": "SearchResult",
  "description": "search result",
  "properties": {
    "aliases": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "example": [
        "example"
      ]
    },
    "companies": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "example": [
        "example"
      ]
    },
    "companyType": {
      "type": "string",
      "example": "example"
    },
    "country": {
      "type": "string",
      "example": "usa"
    },
    "director": {
      "type": "string",
      "example": "example"
    },
    "first_air_time": {
      "type": "string",
      "example": "example"
    },
    "genres": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "example": [
        "example"
      ]
    },
    "id": {
      "type": "string",
      "example": "abc123"
    },
    "image_url": {
      "type": "string",
      "example": "https://artworks.thetvdb.com/banners/example.jpg"
    },
    "name": {
      "type": "string",
      "example": "Example Name"
    },
    "is_official": {
      "type": "boolean",
      "example": true
    },
    "name_translated": {
      "type": "string",
      "example": "example"
    },
    "network": {
      "type": "string",
      "example": "example"
    },
    "objectID": {
      "type": "string",
      "example": "abc123"
    },
    "officialList": {
      "type": "string",
      "example": "example"
    },
    "overview": {
      "type": "string",
      "example": "A descriptive paragraph of text."
    },
    "overviews": {
      "description": "translation simple record",
      "additionalProperties": {
        "type": "string"
      },
      "example": {
        "ara": "\u062a\u062f\u0648\u0631 \u0642\u0635\u0629 \u0627\u0644\u0645\u0633\u0644\u0633\u0644 \u062d\u0648\u0644...",
        "ces": "B\u011bhem letu \u010d. 815 spole\u010dnosti Oceanic...",
        "deu": "Im Bruchteil einer Sekunde ger\u00e4t das Leben..."
      },
      "type": "object"
    },
    "overview_translated": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "example": [
        "example"
      ]
    },
    "poster": {
      "type": "string",
      "example": "example"
    },
    "posters": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "example": [
        "example"
      ]
    },
    "primary_language": {
      "type": "string",
      "example": "example"
    },
    "remote_ids": {
      "items": {
        "description": "remote id record",
        "properties": {
          "id": {
            "type": "string",
            "x-go-name": "ID",
            "example": "abc123"
          },
          "type": {
            "format": "int64",
            "type": "integer",
            "x-go-name": "Type",
            "example": 12345
          },
          "sourceName": {
            "type": "string",
            "x-go-name": "SourceName",
            "example": "example"
          }
        },
        "type": "object",
        "x-go-package": "github.com/whip-networks/tvdb-api-v4-core/tvdb-api-v4-core/pkg/model"
      },
      "type": "array",
      "x-go-name": "RemoteIDs"
    },
    "status": {
      "type": "string",
      "x-go-name": "Status",
      "example": "Continuing"
    },
    "slug": {
      "type": "string",
      "example": "example-slug"
    },
    "studios": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "example": [
        "example"
      ]
    },
    "title": {
      "type": "string",
      "example": "example"
    },
    "thumbnail": {
      "type": "string",
      "example": "example"
    },
    "translations": {
      "description": "translation simple record",
      "additionalProperties": {
        "type": "string"
      },
      "example": {
        "ara": "\u062a\u062f\u0648\u0631 \u0642\u0635\u0629 \u0627\u0644\u0645\u0633\u0644\u0633\u0644 \u062d\u0648\u0644...",
        "ces": "B\u011bhem letu \u010d. 815 spole\u010dnosti Oceanic...",
        "deu": "Im Bruchteil einer Sekunde ger\u00e4t das Leben..."
      },
      "type": "object"
    },
    "translationsWithLang": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "example": [
        "example"
      ]
    },
    "tvdb_id": {
      "type": "string",
      "example": "abc123"
    },
    "type": {
      "type": "string",
      "example": "example"
    },
    "year": {
      "type": "string",
      "example": "2024"
    }
  },
  "type": "object"
}

=== api-evangelist/tvdb/examples/tvdb-search-result-example.json
{
  "aliases": [
    "example"
  ],
  "companies": [
    "example"
  ],
  "companyType": "example",
  "country": "usa",
  "director": "example",
  "first_air_time": "example",
  "genres": [
    "example"
  ],
  "id": "abc123",
  "image_url": "https://artworks.thetvdb.com/banners/example.jpg",
  "name": "Example Name",
  "is_official": true,
  "name_translated": "example",
  "network": "example",
  "objectID": "abc123",
  "officialList": "example",
  "overview": "A descriptive paragraph of text.",
  "overviews": {
    "ara": "\u062a\u062f\u0648\u0631 \u0642\u0635\u0629 \u0627\u0644\u0645\u0633\u0644\u0633\u0644 \u062d\u0648\u0644...",
    "ces": "B\u011bhem letu \u010d. 815 spole\u010dnosti Oceanic...",
    "deu": "Im Bruchteil einer Sekunde ger\u00e4t das Leben..."
  },
  "overview_translated": [
    "example"
  ],
  "poster": "example",
  "posters": [
    "example"
  ],
  "primary_language": "example",
  "remote_ids": [
    {
      "id": "abc123",
      "type": 12345,
      "sourceName": "example"
    }
  ],
  "status": "Continuing",
  "slug": "example-slug",
  "studios": [
    "example"
  ],
  "title": "example",
  "thumbnail": "example",
  "translations": {
    "ara": "\u062a\u062f\u0648\u0631 \u0642\u0635\u0629 \u0627\u0644\u0645\u0633\u0644\u0633\u0644 \u062d\u0648\u0644...",
    "ces": "B\u011bhem letu \u010d. 815 spole\u010dnosti Oceanic...",
    "deu": "Im Bruchteil einer Sekunde ger\u00e4t das Leben..."
  },
  "translationsWithLang": [
    "example"
  ],
  "tvdb_id": "abc123",
  "type": "example",
  "year": "2024"
}
